# Generated by Django 6.0 on 2026-01-27 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_flashsale_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsalenotification',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='flashsalenotification',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flashsalenotification',
            name='flash_sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.flashsale'),
        ),
        migrations.AlterField(
            model_name='flashsalenotification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
