# Generated by Django 6.0 on 2026-01-15 12:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_productimage_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_percentage', models.PositiveIntegerField(help_text='Chegirma foizi (1-99)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Chegirmadagi narx', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Chegirma uchun mavjud mahsulot soni')),
                ('sold_quantity', models.PositiveIntegerField(default=0, help_text='Sotilgan mahsulotlar soni')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('active', 'Faol'), ('expired', 'Tugagan'), ('cancelled', 'Bekor qilingan')], default='scheduled', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='product.product')),
            ],
            options={
                'verbose_name': 'Flash Sale',
                'verbose_name_plural': 'Flash Sales',
                'db_table': 'flash_sale',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FlashSaleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.flashsale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['start_time', 'end_time'], name='flash_sale_start_t_0ff35a_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['status', 'is_active'], name='flash_sale_status_831afa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flashsalenotification',
            unique_together={('user', 'flash_sale')},
        ),
    ]
